name: average_ensembled_policy
comment: "Ensembled policy with averaged weights"
seed: 42
use_wandb: true
eval_repeats_after_training: 1
use_tensorboard: false
device: cuda
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,4}
engine_iters_per_env_step: 4
num_robots: 16
time_steps_per_batch: 128
epochs_per_batch: 5
frames_per_sub_batch: 4096
eval_and_save_every: 10
max_eval_steps: 1000
optimizer: ${cls:torch.optim.AdamW}
scheduler: ${cls:torch.optim.lr_scheduler.LinearLR}
scheduler_opts:
  start_factor: 1.0
  end_factor: 0.28703006303809225
  total_iters: ${intdiv:${total_frames},${mul:${time_steps_per_batch},${num_robots}}}
max_grad_norm: 0.5
grid_res: 0.05
max_coord: 3.2
# start important
heightmap_gen: ${ cls:flipper_training.heightmaps.pallets.FixedPalletHeightmapGenerator}
heightmap_gen_opts:
  x_offset: 0.0        
  y_offset: 0.0        
  yaw: 1.57     
  length: 1.2
  width: 0.8
  height: 0.144
objective: ${cls:flipper_training.rl_objectives.fixed_goal.FixedStartGoalNavigation}
objective_opts:
  start_x_y_z: ${tensor:[-1.5, 0.0, 0.2]}
  goal_x_y_z: ${tensor:[1.5, 0.0, 0.2]}
  iteration_limit: 1000
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  goal_reached_threshold: 0.35
  init_joint_angles: ${tensor:[0.0,0.0,0.0,0.0]}
  resample_random_joint_angles_on_reset: false
# end important
world_opts:
  k_stiffness: 30000
  k_friction_lon: 1.0
  k_friction_lat: 0.8
engine_opts:
  damping_alpha: 5.0
  dt: 0.007
engine_compile_opts:
  options:
    triton.cudagraphs: true
  fullgraph: true
  correctness_iters: 10
  benchmark_iters: 1000
  atol: 0.1
  rtol: 1.0e-06
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05
vecnorm_opts:
  decay: 0.99
  eps: 0.0001
vecnorm_on_reward: true
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      apply_noise: true
      noise_scale: 1.0e-02
      encoder_opts:
        num_hidden: 2
        hidden_dim: 64
        output_dim: 64
        layernorm: true
  - cls: ${cls:flipper_training.observations.heightmap.Heightmap}
    opts:
      apply_noise: true
      noise_scale: 1.0e-02
      percep_shape:
        - 64
        - 64
      percep_extent:
        - 1.0
        - 1.0
        - -1.0
        - -1.0
      interval:
        - -1.0
        - 1.0
      normalize_to_interval: false
      encoder_opts:
        output_dim: 64
gae_opts:
  gamma: 0.999
  lmbda: 0.95
  average_gae: false
  skip_existing: false
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: true
  separate_losses: false
data_collector_opts:
  compile_policy: false
  split_trajs: false
  exploration_type: RANDOM
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoalWithPenaltiesConfigurable}
reward_opts:
  goal_reached_reward: 7.963765459661249
  failed_reward: -7.737836592755915
  shaping_coef: 38.23252716396916
  gamma: ${gae_opts.gamma}
  step_penalty: -0.37878885469543
  joint_vel_variance_coef: 0.12175687152820583
  joint_angle_variance_coef: 0.08011397434183266
  track_vel_variance_coef: 0.2876607076073408
  roll_coef: 0.1
  roll_rate_coef: 0.1
  pitch_coef: 0.1
  pitch_rate_coef: 0.1
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
policy_opts:
  share_encoder: false
  apply_baselines_init: true
  actor_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: false
  value_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: true
  actor_optimizer_opts:
    lr: 0.0004824297168107223
    weight_decay: 0.0001
  value_optimizer_opts:
    lr: 0.0023065521662259366
    weight_decay: 0.0001
policy_weights_path: modified_networks/top_3_averaged/policy.pth
vecnorm_weights_path: modified_networks/top_3_averaged/vecnorm.pth
